### ISSUE TITLE
load_glyphs() not working in v1.5.2 (worked in v1.5.1)

### ISSUE THREAD

**Issue by anecdata** [adafruit/Adafruit_CircuitPython_Bitmap_Font#51] opened 2021-11-18 04:26 UTC
Tested on Espressif, SAMD51, SAMD21, RP2040. PyPortal demo:

```
Adafruit CircuitPython 7.1.0-beta.0 on 2021-11-12; Adafruit PyPortal with samd51j20
>>> 
>>> from adafruit_bitmap_font import bitmap_font
>>> 
>>> bitmap_font.__version__
'1.5.1'
>>> 
>>> # from https://learn.adafruit.com/pyportal-alarm-clock/code-tour
>>> time_font = bitmap_font.load_font('/fonts/Arial-12.bdf')
>>> time_font.load_glyphs(b'0123456789:')
>>> 
```

Replace adafruit_bitmap_font v1.5.1 with adafruit_bitmap_font v1.5.2:

```
Adafruit CircuitPython 7.1.0-beta.0 on 2021-11-12; Adafruit PyPortal with samd51j20
>>> 
>>> from adafruit_bitmap_font import bitmap_font
>>> 
>>> bitmap_font.__version__
'1.5.2'
>>> 
>>> # from https://learn.adafruit.com/pyportal-alarm-clock/code-tour
>>> time_font = bitmap_font.load_font('/fonts/Arial-12.bdf')
>>> time_font.load_glyphs(b'0123456789:')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/adafruit_bitmap_font/bdf.py", line 142, in load_glyphs
OSError: [Errno 22] Invalid argument
>>> 
```

**Comment by FoamyGuy** [comment] 2021-11-18 14:01
It looks to me like the code at line 142 is assuming that `self.file` is an opened file instance.
https://github.com/adafruit/Adafruit_CircuitPython_Bitmap_Font/blob/a3272e2f60d3f00b8e9bab41e9097c85557dc989/adafruit_bitmap_font/bdf.py#L142

tracing back up a bit in the library the file is coming ultimately from here:

https://github.com/adafruit/Adafruit_CircuitPython_Bitmap_Font/blob/a3272e2f60d3f00b8e9bab41e9097c85557dc989/adafruit_bitmap_font/bitmap_font.py#L36-L41

I'm not super familiar with the lifecycle of things that use the `with:` context processor. Is it possible that the return and initializer happening on the same line is resulting in `font_file` getting closed automatically by the end of the `with` block before it has the chance to be used for reading inside of the `load_glyphs()` function?

**Comment by FoamyGuy** [comment] 2021-11-18 14:42
I do think the issue is that the file is being closed before `load_glyphs()` can do anything with it. I verified the same error with this minimal reproducer:
```
>>> f = open("boot_out.txt", "r")
>>> print(f.readline())
Adafruit CircuitPython 7.0.0-alpha.5 on 2021-07-21; Adafruit FunHouse with ESP32S2

>>> f.close()
>>> f.seek(0)
84
>>> print(f.readline())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument

```

**Comment by anecdata** [comment] 2021-11-18 15:19
I think you're right, the file `diff` seemed to point to that too.

**Comment by tannewt** [comment] 2021-11-18 18:08
We should probably switch this to a filename as well.

**Comment by jposada202020** [comment] 2023-02-15 16:16
Is there any work to be done here? or #52 solved the issue. Happy to help if needed :)

**Comment by anecdata** [comment] 2023-02-15 19:32
As far as I know, this was fixed in 1.5.3, and versions starting then have been loading fonts and glyphs fine.

**Comment by jposada202020** [comment] 2023-02-15 19:45
I think I will test it with https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/blob/main/examples/display_text_advance_example.py , and if everything goes well and you agree Ill close the issue :)

**Comment by jposada202020** [comment] 2023-02-15 21:44
You were right, no issues detected. Tested on 
```py
Adafruit CircuitPython 8.0.0 on 2023-02-06; Adafruit PyPortal Titano with samd51j20
```

Using https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/blob/main/examples/display_text_advance_example.py

LGTM thanks

**Closed as completed by jposada202020** 2023-02-15 21:44 UTC
Labels: bug
